apiVersion: v1
kind: Service
metadata:
  name: autos-api-paul-lb
spec:
  type: LoadBalancer
  selector:
    app: autos-api-paul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
