apiVersion: v1
kind: Service
metadata:
  name: auto-api-pc-lb
spec:
  type: LoadBalancer
  selector:
    app: auto-api-pc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
